project:
  type: website

website:
  title: "arewadsdemo"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lukmanaj
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



